# Generated by Django 4.2 on 2024-12-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('composition', models.TextField(blank=True, null=True)),
                ('uses', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('substitutes', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
